pivotal:
  app:
    symbols:
      it: EMC,IBM,VMW
      fs: JPM,C,MS
---
spring:
  profiles: local
  jpa:
     hibernate:
        ddl-auto: update
server:
  port: 8080
---
spring:
  profiles: cloud
  jpa:
     hibernate:
        ddl-auto: update
