pivotal:
  app:
    symbols:
      it: EMC,VMW,HP,APPL
      fs: JPM,C,MS,BAC,GS,WFC,TDA
---
spring:
  profiles: local
  jpa:
     hibernate:
        ddl-auto: update
server:
  port: 8080
---
spring:
  profiles: cloud
  jpa:
     hibernate:
        ddl-auto: update
